apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla
data:
  liveness-probe.sh: |
    #!/bin/bash
    CQLSH_HOST=$(hostname -i) cqlsh -e "CREATE KEYSPACE IF NOT EXISTS furan WITH REPLICATION = { 'class': 'SimpleStrategy', 'replication_factor': 1 } AND DURABLE_WRITES = true;"
