// Code generated by "stringer -type=NotificationEvent"; DO NOT EDIT.

package notifier

import "strconv"

const _NotificationEvent_name = "CreateEnvironmentUpdateEnvironmentDestroyEnvironmentSuccessFailureEnvironmentLimitExceeded"

var _NotificationEvent_index = [...]uint8{0, 17, 34, 52, 59, 66, 90}

func (i NotificationEvent) String() string {
	if i < 0 || i >= NotificationEvent(len(_NotificationEvent_index)-1) {
		return "NotificationEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NotificationEvent_name[_NotificationEvent_index[i]:_NotificationEvent_index[i+1]]
}
