// Code generated by "stringer -type=NotificationEvent"; DO NOT EDIT.

package notifier

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CreateEnvironment-0]
	_ = x[UpdateEnvironment-1]
	_ = x[DestroyEnvironment-2]
	_ = x[Success-3]
	_ = x[Failure-4]
	_ = x[EnvironmentLimitExceeded-5]
}

const _NotificationEvent_name = "CreateEnvironmentUpdateEnvironmentDestroyEnvironmentSuccessFailureEnvironmentLimitExceeded"

var _NotificationEvent_index = [...]uint8{0, 17, 34, 52, 59, 66, 90}

func (i NotificationEvent) String() string {
	if i < 0 || i >= NotificationEvent(len(_NotificationEvent_index)-1) {
		return "NotificationEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NotificationEvent_name[_NotificationEvent_index[i]:_NotificationEvent_index[i+1]]
}
