# Default values for vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: quay.io/dollarshaveclub/vault-dev
  tag: master
  pullPolicy: Always

service:
  name: vault
  type: ClusterIP
  ports:
    internalPort: 8200
    externalPort: 8200

keyPrefix: production/furan/
