{{ if .Values.run_migrations }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": 'pre-install,pre-upgrade'
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      serviceAccountName: {{ .Values.serviceaccount }}
      imagePullSecrets:
        - name: "{{ .Values.image.pullSecret }}"
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}-migrations
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /go/bin/acyl
        args:
          - "--secrets-backend"
          - "{{ .Values.app.secrets_backend }}"
          - "--secrets-mapping"
          - "{{ .Values.app.secrets_mapping }}"
          - "pg-migrate"
          - "--postgres-migrations-dir"
          - "/opt/migrations"
          - "--postgres-uri"
          - {{ .Values.postgresql.uri }}
{{ end }}
