// Code generated by "stringer -type=EnvironmentStatus"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownStatus-0]
	_ = x[Spawned-1]
	_ = x[Success-2]
	_ = x[Failure-3]
	_ = x[Destroyed-4]
	_ = x[Updating-5]
}

const _EnvironmentStatus_name = "UnknownStatusSpawnedSuccessFailureDestroyedUpdating"

var _EnvironmentStatus_index = [...]uint8{0, 13, 20, 27, 34, 43, 51}

func (i EnvironmentStatus) String() string {
	if i < 0 || i >= EnvironmentStatus(len(_EnvironmentStatus_index)-1) {
		return "EnvironmentStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnvironmentStatus_name[_EnvironmentStatus_index[i]:_EnvironmentStatus_index[i+1]]
}
