// Code generated by "stringer -type=EventStatusType"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownEventStatusType-0]
	_ = x[CreateEvent-1]
	_ = x[UpdateEvent-2]
	_ = x[DestroyEvent-3]
}

const _EventStatusType_name = "UnknownEventStatusTypeCreateEventUpdateEventDestroyEvent"

var _EventStatusType_index = [...]uint8{0, 22, 33, 44, 56}

func (i EventStatusType) String() string {
	if i < 0 || i >= EventStatusType(len(_EventStatusType_index)-1) {
		return "EventStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventStatusType_name[_EventStatusType_index[i]:_EventStatusType_index[i+1]]
}
