// Code generated by "stringer -type=EventStatus"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownEventStatus-0]
	_ = x[PendingStatus-1]
	_ = x[DoneStatus-2]
	_ = x[FailedStatus-3]
}

const _EventStatus_name = "UnknownEventStatusPendingStatusDoneStatusFailedStatus"

var _EventStatus_index = [...]uint8{0, 18, 31, 41, 53}

func (i EventStatus) String() string {
	if i < 0 || i >= EventStatus(len(_EventStatus_index)-1) {
		return "EventStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventStatus_name[_EventStatus_index[i]:_EventStatus_index[i+1]]
}
