// Code generated by "stringer -type=EventStatus"; DO NOT EDIT.

package models

import "strconv"

const _EventStatus_name = "UnknownEventStatusCreateNewStatusUpdateTearDownStatusUpdateInPlaceStatusDestroyStatusDoneStatusFailedStatus"

var _EventStatus_index = [...]uint8{0, 18, 33, 53, 72, 85, 95, 107}

func (i EventStatus) String() string {
	if i < 0 || i >= EventStatus(len(_EventStatus_index)-1) {
		return "EventStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventStatus_name[_EventStatus_index[i]:_EventStatus_index[i+1]]
}
