// Code generated by "stringer -type=EventStatusType"; DO NOT EDIT.

package models

import "strconv"

const _EventStatusType_name = "UnknownEventStatusTypeCreateEventUpdateEventDestroyEvent"

var _EventStatusType_index = [...]uint8{0, 22, 33, 44, 56}

func (i EventStatusType) String() string {
	if i < 0 || i >= EventStatusType(len(_EventStatusType_index)-1) {
		return "EventStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventStatusType_name[_EventStatusType_index[i]:_EventStatusType_index[i+1]]
}
