// Code generated by "stringer -type=QADestroyReason"; DO NOT EDIT.

package models

import "strconv"

const _QADestroyReason_name = "ReapAgeSpawnedReapAgeFailureReapPrClosedReapEnvironmentLimitExceededCreateFoundStaleDestroyApiRequestEnvironmentLimitExceeded"

var _QADestroyReason_index = [...]uint8{0, 14, 28, 40, 68, 84, 101, 125}

func (i QADestroyReason) String() string {
	if i < 0 || i >= QADestroyReason(len(_QADestroyReason_index)-1) {
		return "QADestroyReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QADestroyReason_name[_QADestroyReason_index[i]:_QADestroyReason_index[i+1]]
}
