# Default values for scylladb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: scylladb/scylla
  tag: 1.6.6
  pullPolicy: Always

service:
  name: scylladb
  type: ClusterIP
  cqlInternalPort: 9042
  cqlExternalPort: 9042

resources: {}
