apiVersion: v1
kind: Service
metadata:
  {{ if .Values.env_name }}
  name: 'furan-{{ .Values.service.name }}'
  {{- else }}
  name: {{ template "scylladb.fullname" . }}
  {{- end }}
  labels:
    app: {{ template "scylladb.name" . }}
    chart: {{ template "scylladb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.cqlExternalPort }}
      name: {{ .Values.service.name }}
      targetPort: {{ .Values.service.cqlInternalPort }}
  selector:
    app: {{ template "scylladb.name" . }}
    release: {{ .Release.Name }}
