// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/dollarshaveclub/acyl/pkg/namegen (interfaces: NameGenerator)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of NameGenerator interface
type MockNameGenerator struct {
	ctrl     *gomock.Controller
	recorder *_MockNameGeneratorRecorder
}

// Recorder for MockNameGenerator (not exported)
type _MockNameGeneratorRecorder struct {
	mock *MockNameGenerator
}

func NewMockNameGenerator(ctrl *gomock.Controller) *MockNameGenerator {
	mock := &MockNameGenerator{ctrl: ctrl}
	mock.recorder = &_MockNameGeneratorRecorder{mock}
	return mock
}

func (_m *MockNameGenerator) EXPECT() *_MockNameGeneratorRecorder {
	return _m.recorder
}

func (_m *MockNameGenerator) New() (string, error) {
	ret := _m.ctrl.Call(_m, "New")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockNameGeneratorRecorder) New() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "New")
}
