apiVersion: v1
kind: Service
metadata:
  {{ if .Values.env_name }}
  name: 'furan-{{ .Values.service.name }}'
  {{- else }}
  name: {{ .Values.service.name }}
  {{- end }}
  labels:
    app: {{ template "kafka.name" . }}
    chart: {{ template "kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "kafka.name" . }}
    release: {{ .Release.Name }}
