apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    app: {{ template "vault.name" . }}
    chart: {{ template "vault.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "vault.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "vault.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vault
          configMap:
            name: vault
            defaultMode: 420
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VAULT_SECRETS_FILE
              value: /vault-secrets/secrets.json
          volumeMounts:
            - name: vault
              mountPath: /vault-secrets
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.internalPort }}
              protocol: TCP
