# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: confluentinc/cp-zookeeper
  tag: 4.0.1
  pullPolicy: Always

livenessProbe:
  initialDelaySeconds: 100
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  httpGet:
    path: "/"

readinessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 2
  successThreshold: 1
  failureThreshold: 1
  httpGet:
    path: "/"

service:
  name: zookeeper
  internalPort: 2181
  externalPort: 2181
