// Code generated by "stringer -type=GitHubEventType"; DO NOT EDIT.

package ghevent

import "strconv"

const _GitHubEventType_name = "UnknownEventPullRequestEventCommitPushEvent"

var _GitHubEventType_index = [...]uint8{0, 12, 28, 43}

func (i GitHubEventType) String() string {
	if i < 0 || i >= GitHubEventType(len(_GitHubEventType_index)-1) {
		return "GitHubEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GitHubEventType_name[_GitHubEventType_index[i]:_GitHubEventType_index[i+1]]
}
