// Code generated by "stringer -type=GitHubEventType"; DO NOT EDIT.

package ghevent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownEvent-0]
	_ = x[PullRequestEvent-1]
}

const _GitHubEventType_name = "UnknownEventPullRequestEvent"

var _GitHubEventType_index = [...]uint8{0, 12, 28}

func (i GitHubEventType) String() string {
	if i < 0 || i >= GitHubEventType(len(_GitHubEventType_index)-1) {
		return "GitHubEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GitHubEventType_name[_GitHubEventType_index[i]:_GitHubEventType_index[i+1]]
}
